#!/bin/csh  
#
#foreach i (`ls *.f *.h */*.f */*.h`)
#
foreach i (`/bin/ls *`)
echo '*******'
echo $i
  diff -b -B -i --ignore-all-space --expand-tabs  $i /home/nielsen/saga50/src/gama/common/$i
end 
