      SUBROUTINE EXCHNG(*,EKFST,EKNEW,EKOLD,EKAVR,
     $ALFNEW,ALFOLD,ALFAVR,AVROLD,AVRNEW,MODEN,msp,xts,xold)
      REAL*8 EKFST,EKOLD,EKNEW,EKAVR
      DIMENSION EKNEW(MODEN),EKFST(MODEN),EKOLD(MODEN),EKAVR(MODEN)
      DIMENSION AVROLD(MODEN),AVRNEW(MODEN)
      DIMENSION ALFNEW(MODEN),ALFOLD(MODEN),ALFAVR(MODEN)
      COMMON/LUNIT/MSOURC,MODOLD,MODNEW,LUPRT
      COMMON/NRNGD/HNEW,HOLD,RSTART,REND,SLNGTH,IND1
      COMMON/N/MINMOD,MAXMOD,HORIG,NFREQ
      DIMENSION XTS(moden,MSP),Xold(moden,MSP)
C
      MODQTY=MAXMOD-MINMOD+1
C
      DO 2000 IM=1,MODQTY
      EKAVR(IM)=EKAVR(IM)+0.5*(EKNEW(IM)+EKOLD(IM))*(REND-RSTART)
      ALFAVR(IM)=ALFAVR(IM)+0.5*(ALFNEW(IM)+ALFOLD(IM))*(REND-RSTART)
2000  CONTINUE
C
      DO 1000 IM=1,MODQTY
         do ik=1,msp
           xold(im,ik)=xts(im,ik)
         enddo
      EKOLD(IM)=EKNEW(IM)
      ALFOLD(IM)=ALFNEW(IM)
      AVROLD(IM)=AVRNEW(IM)
1000  CONTINUE
C
      RSTART=REND
      REND=REND+SLNGTH
      HOLD=HNEW
      RETURN 1
      END
