      SUBROUTINE FILE(prtfil)
C
C   BASIC FILES TO BE USED THROUGHOUT THE EXECUTION
C   ARE ASSIGNED HERE.
C
      integer prtfil
      CHARACTER*1 DOLLAR
      CHARACTER*3 VAXFPS
      CHARACTER*4 EOF
      CHARACTER*40 FILENM

      COMMON /LUNIT/ MSOURC, MODOLD, MODNEW, LUPRT
      real*8  twopi
      common /twopie/twopi

      DATA MSOURC,MODOLD,MODNEW/11,12,13/
C
  100 FORMAT(A1)
  120 FORMAT(A4)
  180 FORMAT(1X,' ERROR IN SEARCHING INPUT FILE NAME ',/,
     & 1X,A80)

C   SUB FILE        6, 9, 10, 11, 12, 13, 14, 15, 16, 18, 20
C   SUB TLRAN       92
 
      TWOPI=2.0D0*DACOS(-1.0D0)

       LUPRT=prtfil
c       LUPRT=6
C
C
C   THE OUTPUT FILE NAME FOR OPTION PULSE IS DERIVED FROM THE
C   INPUT FILE NAME. SEE DETAILS IN SUB PULSE.FOR.
C
 2000 CONTINUE

      RETURN
       END

       SUBROUTINE FILOLD (MODQTY,MSP,XTS,EKFST,EKNEW,EKOLD,
     & EKAVR,ALFNEW,ALFOLD,ALFAVR,AVROLD,AVRNEW,MODEN,xsou,xold)
       REAL*8 EKAVR(MODEN),EKFST(MODEN),EKOLD(MODEN),EKNEW(MODEN)
       DIMENSION XTS(moden,MSP),Xsou(moden,MSP),Xold(moden,MSP)
       dimension ALFAVR(MODEN),ALFNEW(MODEN),ALFOLD(MODEN)
       DIMENSION AVROLD(MODEN),AVRNEW(MODEN)
       COMMON /LUNIT/ MSOURC, MODOLD, MODNEW, LUPRT
C
C  INITIAL FILLING OF FILES #11 AND 12 (MODE AMPLITUDES 
C  AT INITIAL RANGE AND BEGIN OF SECTOR, RESPECTIVELY
C
C
       DO 3000 IM=1,MODQTY
         do ik=1,msp
            xsou(im,ik)=xts(im,ik)
            xold(im,ik)=xts(im,ik)
         enddo
        EKFST(IM)=EKNEW(IM)
        EKOLD(IM)=EKNEW(IM)
        ALFOLD(IM)=ALFNEW(IM)
        EKAVR(IM)=0.0
        ALFAVR(IM)=0.0
        AVROLD(IM)=AVRNEW(IM)
3000   CONTINUE
      RETURN
      END
