      SUBROUTINE REVISE(MY,NMODES,NMOD,NMES,IOLD,N,NS,*)
      REAL*8 MY(8,NMODES)
      DIMENSION N(8), NS(8)
      COMMON/LUNIT/MSOURC,MODOLD,MODNEW,LUPRT
C
  100 FORMAT(1X,' MAXIMUM SEQUENCE OF MESHES (8) HAS',
     &' BEEN UNSUCCESSFULLY TRIED.',/,'  INCREASE MAXIMUM',
     &' NUMBER OF MESH POINTS. ',/,'  EXECUTION IS TERMINATED')
  200 FORMAT(1X,//,' THE NUMBER OF MESHES HAS BEEN INCREASED AND'
     & ,/,' THE MESH POINTS REDEFINED IN THE ATTEMPT TO ',/,
     & ' ACHIEVE ACCURATE EXTRAPOLATION.')
C
      IF(NMOD.EQ.1)   RETURN
C
      I=IOLD
      DO 3000   M=NMOD,2,-1
      IF(MY(I,M).GE.MY(I,M-1))   THEN
C
      IF(NMES.EQ.8)   THEN
      WRITE(LUPRT,100)
      STOP
      END IF
C
      DO 1000   I=IOLD,8
      N(I-IOLD+1)=N(I)
      NS(I-IOLD+1)=NS(I)
 1000 CONTINUE
      DO 1200   I=10-IOLD,8 
      N(I)=N(I-3)*2
      NS(I)=NS(I-3)*2
 1200 CONTINUE

      NMES1=MIN(8,NMES+2)
C
      WRITE(LUPRT,200)
      NMES=NMES1
      RETURN 1
      END IF
 3000 CONTINUE
      RETURN
      END
