#!/bin/csh  
#
#foreach i (`ls *.f *.h */*.f */*.h`)
#
foreach i (`/bin/ls *.f *.h Makefile`)
echo '*******'
echo $i
  diff -b -B -i --ignore-all-space --expand-tabs  $i /mpl/gerstoft/saga/src022007/$i
end 
