#!/bin/csh  
#
#foreach i (`ls *.f *.h */*.f */*.h`)
foreach i (`ls  ../cprosiminit.f ../cprosiminter.f ../comcprosim.h ../gen_i_o_saga.h *.f *.h *com Makefile`)
echo '*******'
echo $i
#  diff $i $HOME/SAGA/src/$i
  diff $i /nfs/aosf14/usr3/users/nielsen/saga/src/cprosim/$i
end 
