!: 	EDIT THIS PARAMETER FILE IF PROGRAM DOES NOT COMPILE BECAUSE THE 
!:	STORAGE REQUIREMENTS ARE TOO GREAT (DECREASE SIZES) OR IF YOUR RUN
!:	PARAMETERS RESULT IN A "STORAGE EXCEEDED" MESSAGE (INCREASE SIZES).
!: NLMAX =	GEOACOUSTIC PARAMETER ARRAYS
!:		(total # layers in SVP, bottom, and top + 2)
!: NTLMAX = 	TRANSMISSION LOSS ARRAYS FOR CW CALCULATIONS
!: 		(# src depths) * (# rec depths) * (# ranges)
!:		REFLECTION COEFF ARRAYS FOR REFLECTION COEFF CALCULATIONS
!:		(# plane wave angles) * (# frequencies)
!:		R1R2 ARRAYS FOR K-PLANE IMAGES
!:		(# points on real k-axis) * (# points on imag k-axis)
!: NSRMAX = 	SOURCE AND RECEIVER DEPTH ARRAYS
!:		(# source depths + # receiver depths)
!: 		GRAZING ANGLE AXIS FOR REFLECTION COEFF CALCULATIONS
!:		(# grazing angles)
!: NRNGMAX =	SOURCE-RECEIVER RANGES OR SOURCE TRACK POINTS
!:		(# source-receiver ranges) or (# points on source track)
!: NSNRMAX =	SOURCE-RECEIVER RANGE ARRAYS 
!:		(# receivers) * (# ranges)
!: NSEGMAX = 	SOURCE TRACK ARRAYS
!:		(# source track segments specified for iitl=2 or iifft=2)
!: NM_MAX =	MODE CHARACTERISTICS ARRAYS
!:		(# modes)
!: NSR_NM_MAX =	MODE FUNCTION ARRAYS
!:		(# source depths + # receiver depths) * (# modes)
!: NTFMAX =	TRANSFER FUNCTION ARRAY FOR BROADBAND CALCULATIONS
!: 		(# FFT freqs)*(# rec depths)*(# src-rec ranges)
!: NFBBMAX =	FREQUENCY AXIS ARRAY FOR BROADBAND CALCULATIONS
!:		[# freqs to compute transfer function=(fmax-fmin)/(fs/nfft)]
!: NFCWMAX =	FREQUENCY AXIS ARRAY FOR CW & REFL COEFF CALCULATIONS
!:		(# frequencies)
!: NM_NF_MAX = 	EIGENVALUE ARRAYS FOR BROADBAND CALCULATIONS
!:		(# modes at fmax) * (# FFT freqs)
!: NZ_NF_MAX = 	MODE FUNCTION ARRAYS FOR BROADBAND CALCULATIONS
!:		(# src/rec depths ) * (# FFT freqs)
!: NDMAX =      MAXIMUM NUMBER OF DUCTS IN A PROFILE
!: NPMAX =      MAXIMUM NUMBER OF ENVIRONMENTAL PARAMETERS TO VARY
!: NRECL =      DIRECT ACCESS FILE CONVENTION FOR recl=lenrec COMMAND:
!:              SET NRECL=1 FOR LENREC IN WORDS (SGI,ALPHA),
!:              NRECL=4 FOR LENREC IN BYTES (SUN).
!: SUFX =	OUTPUT FILE SUFFIX DELIMITER ('_' or '.', FOR EXAMPLE)
MODULE parms_com
IMPLICIT NONE
SAVE

INTEGER*4 :: NTLMAX
INTEGER*4 :: NTFMAX,NFBBMAX,NM_NF_MAX,NZ_NF_MAX,NSNRMAX
INTEGER*4 :: NHDFMAX
CHARACTER(len=1), PARAMETER :: SUFX='_'
CHARACTER*128 MLINE
INTEGER*4, PARAMETER :: NLMAX=100,NSRMAX=10000,NRNGMAX=10000,&
	NFCWMAX=1000,NPMAX=50,NRECL=4,LML=67
!NM_MAX=10000,NSR_NM_MAX=500000,
INTEGER*4, PARAMETER :: NSEGMAX=50,NDMAX=40
!     parameter(NLMAX=40,NTLMAX=1000000,NSRMAX=3000,
!    .   NRNGMAX=5000,NM_MAX=10000,NSR_NM_MAX=1000000,NTFMAX=40960000,
!    .   NFBBMAX=8192,NM_NF_MAX=2000000,NZ_NF_MAX=200000,NRECL=4,
!    .   NSNRMAX=1000000,NSEGMAX=50,NHDFMAX=max(NTLMAX,NM_NF_MAX),
!    .   NDMAX=40,NPMAX=25,SUFX='_',MLINE='MEMORY LIMIT EXCEEDED!  '//
!    .   'CHECK INPUTS OR CHANGE LIMITS IN parms_com.',LML=67)
END MODULE parms_com
