C
C     COMMON BLOCKS OF ARRAYS THE SIZE OF WHICH DEPEND ON
C     THE MAXIMUM NUMBER OF LAYERS NLA.
C
C     LOCAL COEFFICIENT MATRICES AND RIGHT HAND SIDES
C
      COMPLEX ALO(NLA,4,4),AUP(NLA,4,4),R(NLA,4),SS(NLA,4)
      COMMON /FIELD/ ALO,AUP,R,SS
      COMPLEX ROIN(NLA,4),RUIN(NLA,4)
      COMMON /LRHS/ ROIN,RUIN
C
C     ENVIRONMENTAL PARAMETERS AND WAVENUMBERS
C
      COMPLEX AK(NLA,2),AK2(NLA,2),ALAME(NLA,2)
      COMPLEX ALFA(NLA),BETA(NLA)
      REAL V(NLA,6),THICK(NLA)
      COMMON /LAYDAT/ V,AK,AK2,ALAME,THICK,ALFA,BETA
      COMMON /LAYTYP/ LAYTYP(NLA),NUMT(NLTYP),LAYT(NLA,NLTYP)
C
C     FUNCTIONS OF WAVENUMBERS
C
      COMPLEX EZALFA(NLA),EZBETA(NLA),EZALFM(NLA),EZBETM(NLA)
      COMPLEX CON1(NLA),CON2(NLA),CON3(NLA),CON4(NLA)
      REAL RCON1(NLA)
      COMMON /VARS5/ LSOLF,LSOLL,NSOL,EZALFA,EZBETA,
     &               EZALFM,EZBETM,RCON1,CON1,CON2,CON3,CON4
C
C     MAPPING POINTERS AND GLOBAL SYSTEM SIZE PARAMETERS
C
      COMPLEX RHS(NLA3*nla3)    
      COMMON /EQVAR/ NEQ,IPS(NLA,4),ICP(NLA2),IRN(NLA1),IDP(NLA3),
     &               NNA,ISTART(NLA),IRST(NLA),ICST(NLA),NCL(NLA),
     &               NRI(NLA),RHS,IBW,EPS,IRHCOL,NNB
c
c     POINTER ARRAYS SHOULD BE REAL IF APAL64 VERSION OF CVIMOV
C     AND CVMOVI ARE USED ON THE FPS164
C
C     REAL INDA(NLA1),INDR(NLA3),INDS(NLA3),INDB(NLA1)
      INTEGER INDA(NLA1),INDR(NLA3),INDS(NLA3),INDB(NLA1)
      COMMON /INDEX/ INDA,INDR,INDS,INDB
C
C     SOURCE PARAMETERS
C
      COMMON /LAYSOU/ NOSOU(NLA),IFSOU(NLA),ILSOU(NLA)
C
C     ROUGH SURFACE SCATTERING PARAMETERS
C
      COMMON /SCATCO/ ROUGH(NLA),ROUGH2(NLA)
      real clen(nla)
      COMMON /NKIRCH/ CLEN,DLWNK(NLA),IMX(NLA)
C
C     TRANSVERSE ISOTROPY
C
      COMPLEX ASP(3,NLA),BSP(3,NLA)
      COMMON /TISO/ NTISOL,NSL(NLA),ASP,BSP,ARO(3,NLA),
     &              AH(3,NLA),LAYNTI(NLA) 
      COMPLEX ANSTD(26,NLA)
      COMMON /ANSTD/ ANSTD
C
C     Airy function solution
C
      COMPLEX ACO(NLA),BCO(NLA),CCO(NLA),AISC(NLA),BISC(NLA)
      COMMON /AIRYCO/ ACO,BCO,CCO,AISC,BISC
C
C     WORKING ARRAYS
C
      COMPLEX WORK1(IBSI),WORK2(IBSI)
      COMMON /WORK/ WORK1,WORK2

