C
C     THE FOLLOWING SUBROUTINES SIMULATE THE ASSYNCHRONOUS
C     IO USED ON THE FPS164
C
      SUBROUTINE OPNBUF(IUN,LREC,NREC,IBUFSIZ)
      CHARACTER*60 FILENM
      COMMON /AIOBUF/ IBUF(99),NOFR(99),IRECAC(99),NPRREC(99),
     1  ICOUNT(99),TOGGLE(99),IB1(99),IB2(99),IOFF(99),IREC(99),
     2  IRSIZE(99),ISTART(99),IOPN(99)
C    DATA IOPN /99*0/
C 100  FORMAT('FOR00',I1,'.TMP')
C 200  FORMAT('FOR0',I2,'.TMP')
      IF (IUN.GT.99.OR.IUN.LT.1) THEN
      CALL AIOERR('OPNBUF',IUN,1)
      END IF
      IF (IOPN(IUN).EQ.1) THEN
      CALL AIOERR('OPNBUF',IUN,3)
      ELSE
      IOPN(IUN)=1
      END IF
C
      OPEN(UNIT=IUN,STATUS='SCRATCH',FORM='UNFORMATTED')
C      NBYTRC=4*LREC
C      IF (IUN.LT.10) THEN
C        WRITE(FILENM,100) IUN
C      ELSE
C        WRITE(FILENM,200) IUN
C      END IF
C      OPEN(UNIT=IUN,FILE=FILENM,FORM='BINARY',RECL=NBYTRC)
      RETURN
      END
C
C
      SUBROUTINE ENFBUF(IUN)
      COMMON /AIOBUF/ IBUF(99),NOFR(99),IRECAC(99),NPRREC(99),
     1  ICOUNT(99),TOGGLE(99),IB1(99),IB2(99),IOFF(99),IREC(99),
     2  IRSIZE(99),ISTART(99),IOPN(99)
      IF (IOPN(IUN).NE.1) THEN
      CALL AIOERR('ENFBUF',IUN,2)
      END IF
      ENDFILE(IUN)
      RETURN
      END
C
C
      SUBROUTINE RWDBUF(IUN)
      COMMON /AIOBUF/ IBUF(99),NOFR(99),IRECAC(99),NPRREC(99),
     1  ICOUNT(99),TOGGLE(99),IB1(99),IB2(99),IOFF(99),IREC(99),
     2  IRSIZE(99),ISTART(99),IOPN(99)
C
      IF (IOPN(IUN).NE.1) THEN
      CALL AIOERR('RWDBUF',IUN,2)
      END IF
      REWIND(IUN)
      RETURN
      END
C
C
      SUBROUTINE CLSBUF(IUN)
      COMMON /AIOBUF/ IBUF(99),NOFR(99),IRECAC(99),NPRREC(99),
     1  ICOUNT(99),TOGGLE(99),IB1(99),IB2(99),IOFF(99),IREC(99),
     2  IRSIZE(99),ISTART(99),IOPN(99)
      IF (IOPN(IUN).NE.1) THEN
      CALL AIOERR('CLSBUF',IUN,2)
      ELSE
      IOPN(IUN)=0
      END IF
      CLOSE(UNIT=IUN,STATUS='DELETE')
      RETURN
      END
C
C
      SUBROUTINE WRBUF(IUN,C,NVAL)
      DIMENSION C(NVAL)
      COMMON /AIOBUF/ IBUF(99),NOFR(99),IRECAC(99),NPRREC(99),
     1  ICOUNT(99),TOGGLE(99),IB1(99),IB2(99),IOFF(99),IREC(99),
     2  IRSIZE(99),ISTART(99),IOPN(99)
      IF (IOPN(IUN).NE.1) THEN
      CALL AIOERR('WRBUF ',IUN,2)
      END IF
C     DO 10 J=1,NVAL
C10     WRITE(IUN) C(J)
      WRITE(IUN) (C(J),J=1,NVAL)
      RETURN
      END
C
C
      SUBROUTINE RDBUF(IUN,C,NVAL)
      DIMENSION C(NVAL)
      COMMON /AIOBUF/ IBUF(99),NOFR(99),IRECAC(99),NPRREC(99),
     1  ICOUNT(99),TOGGLE(99),IB1(99),IB2(99),IOFF(99),IREC(99),
     2  IRSIZE(99),ISTART(99),IOPN(99)
      IF (IOPN(IUN).NE.1) THEN
      CALL AIOERR('RDBUF ',IUN,2)
      END IF
C     DO 10 J=1,NVAL
C10     READ(IUN) C(J)
      READ(IUN) (C(J),J=1,NVAL)
      RETURN
      END
      SUBROUTINE AIOERR(TIT,IUN,IERR)
      CHARACTER*6 TIT
      CHARACTER*30 MESS(10)
      DATA MESS(1) /'*** ILLEGAL LOGICAL UNIT   ***'/
      DATA MESS(2) /'*** FILE NOT OPENED        ***'/
      DATA MESS(3) /'*** FILE ALREADY OPENED    ***'/
      DATA MESS(4) /'*** BUFFER TOO SMALL       ***'/
      DATA MESS(5) /'*** WRITE PAST END OF FILE ***'/
      DATA MESS(6) /'*** WRITE PAST END OF RECD ***'/
      DATA MESS(7) /'*** READ PAST END OF FILE  ***'/
      DATA MESS(8) /'*** READ PAST END OF RECD  ***'/
C
C
 100  FORMAT(1H ,'*** ASYNCHRONOUS IO ERROR   ***')
 200  FORMAT(1H ,'*** SUBROUTINE: ',A6,'      ***')
 300  FORMAT(1H ,'*** UNIT NUMBER:',I6,'      ***')
 400  FORMAT(1H ,'*** ERROR NUMBER:',I5,'      ***')
 500  FORMAT(1H ,A30)
      WRITE(6,100)
      WRITE(6,200) TIT
      WRITE(6,300) IUN
      WRITE(6,400) IERR
      WRITE(6,500) MESS(IERR)
      STOP '*** EXECUTION TERMINATED   ***'
      END
      SUBROUTINE OPFILW(IUN,IOER)
      CHARACTER*40 FILENM
      IOER=0
C
C     OPENS SEQUENCIAL ASCII FILE FOR WRITE
C
C***  VMS
      OPEN(UNIT=IUN,STATUS='NEW',FORM='FORMATTED',ERR=300)
C***  ultrix AND FPS164
C     OPEN(UNIT=IUN,STATUS='UNKNOWN',FORM='FORMATTED',ERR=300)
C***  MS-DOS         
C      IF (IUN.LT.10) THEN
C        WRITE(FILENM,100) IUN
C      ELSE
C        WRITE(FILENM,200) IUN
C      END IF
C 100  FORMAT('FOR00',I1,'.DAT')
C 200  FORMAT('FOR0',I2,'.DAT')
C      OPEN(UNIT=IUN,FILE=FILENM,STATUS='UNKNOWN',FORM='FORMATTED',
C     1     ERR=300)
      RETURN
 300  IOER=1
      RETURN
      END
      SUBROUTINE OPFILR(IUN,IOER)
      CHARACTER*40 FILENM
      IOER=0
C
C     OPENS SEQUENCIAL ASCII FILE FOR READ
C
C***  VMS
      OPEN(UNIT=IUN,STATUS='OLD',ERR=400)
C***  ultrix AND FPS164
C     OPEN(UNIT=IUN,STATUS='OLD',ERR=400)
C***  MS-DOS         
C      IF (IUN.LT.10) THEN
C        WRITE(FILENM,100) IUN
C      ELSE
C        WRITE(FILENM,200) IUN
C      END IF
C      OPEN(UNIT=IUN,FILE=FILENM,STATUS='OLD',ERR=400)
C 100  FORMAT('FOR00',I1,'.DAT')
C 200  FORMAT('FOR0',I2,'.DAT')
      RETURN
 400  IOER=2
      RETURN
      END
