      SUBROUTINE ACCRCY(I,JF2,EK,MY,MODEN,MODQTY,MINMOD,
     & MAXMOD,NMES,H1N,DRAT,ICOUNT,ERR1A,ERR1R,ERR2A,
     & ERR2R,MH0,DH0,DH0SQ,MSED,DSED,*,*)

      INTEGER MH0(8), MSED(8), MH0SQ(8), EXTPOL

      DOUBLE PRECISION H0, H1, H1N
      DOUBLE PRECISION TWOPI, PI, OMEGA, DRAT
      DOUBLE PRECISION ERR1A, ERR1R, ERR2A, ERR2R
      DOUBLE PRECISION WNMIN, EIGREF, EIGMIN, EIGMAX, STIFF
      DOUBLE PRECISION EK(MODEN)
      DOUBLE PRECISION MY(MAXMSH,MODEN)
      DOUBLE PRECISION DH0(8), DSED(8), DH0SQ(8)

      COMMON /AB/ BETA(-1:3), SCATT(2), C2S, C2
      COMMON /EXPMAX/ TRESH, EPS, RRMAX
      COMMON /FLAGPULSE/  EXTPOL, CORREC
      COMMON /GSNAP/ H0, H1, TWOPI, PI, OMEGA
      COMMON /GEN/ EIGREF, EIGMIN, EIGMAX, STIFF
      COMMON /ITMAX/ MAXIT
      COMMON /LUNIT/ LUPLP, LUPLT, LUPRT
      COMMON /PARA2/ NPOINT, MAXMSH

C  100 FORMAT(1X,/,' ADDING ONE MESH (',I2,') AND REPEATING',
C     & ' COMPUTATION ')
C  200 FORMAT(1X,//,' *** WARNING FROM SUB ACCRCY : ',/,
C     & ' MODE CUTOFF ON EXTRAPOLATED EIGENVALUES. ',/, 
C     & ' EXECUTION TERMINATED FOR THIS SOURCE FREQUENCY.')
  340 FORMAT(1X,//,' *** WARNING FOR GROUP VELOCITY CALCULATION AT',
     & ' MESH ',I2,' *** ',/,
     & ' EXTRAPOLATED EIGENVALUES ARE NOT USED BECAUSE OF',
     & ' INSUFFICIENT ACCURACY.',/,
     & ' NON EXTRAPOLATED EIGENVALUES FROM LAST MESH ARE USED',
     & ' INSTEAD.',/,
     & ' MORE DENSE MESHES ARE NEEDED TO IMPROVE ACCURACY ')
  400 FORMAT(1X,/,' WARNING : THE ALLOWED MAX NUMBER OF MESH POINTS',
     & ' IS REACHED. ',/,' LARGER ARRAY SIZES WOULD BE NEEDED ')
  410 FORMAT(1X,/,' EXTRAPOLATED EIGENVALUES ARE CHOSEN. ')
  420 FORMAT(1X,/,' NON EXTRAPOLATED EIGENVALUES ARE CHOSEN. ')
C  500 FORMAT(1X,//,' *** WARNING FOR GROUP VELOCITY CALCULATION AT',
C     & ' MESH ',I2,' *** ',/,
C     & ' THE ACCURACY CRITERIA IS SATISFIED BY THE NON ',/,
C     & ' EXTRAPOLATED EIGENVALUES WHILE MORE DENSE MESHES',/,
C     & ' WOULD STILL BE NEEDED TO IMPROVE ACCURACY ON THE',/,
C     & ' EXTRAPOLATED ONES.',/,
C     & ' NON EXTRAPOLATED EIGENVALUES ARE CHOSEN. ')
  600 FORMAT(1X,//,' ***  MAX NUMBER OF ITERATIONS (',I2,') REACHED',
     & ' IN SUB ACCRCY  ***')
  620 FORMAT(1X,' *** SUB ACCRCY, EPS= ',E12.5,' ***',2X,'ABSOLUTE',
     & 8X,'RELATIVE',/
     & '  MAX ERR ON     EXTRAP WN ',11X,D13.6,3X,D13.6,/,
     & '  MAX ERR ON NON EXTRAP WN ',11X,D13.6,3X,D13.6,/)


      IF(EXTPOL .LE. 0)   THEN
       DO 1200   M=1,MODQTY
       EK(M)=SQRT(MY(I,M))/H0
 1200  CONTINUE
       IF( (NMES .EQ. 1) .OR. (JF2 .EQ. 2) )   RETURN
      END IF 

      WNMIN=OMEGA/DBLE(C2)
      WNMIN=(H0*WNMIN)**2
      CALL CONVRG(ERR1A,ERR1R,ERR2A,ERR2R,MODQTY,NMES,MY,MODEN,
     &            DH0SQ,H0,EK,EXTPOL,WNMIN)
      MAXMOD=MINMOD+MODQTY-1
      IF(MODQTY .LE. 0)   RETURN
      IF(JF2 .EQ. 2)   RETURN

      IF(NMES .GE. 3)   THEN
       NPMAX=(MH0(NMES-2) + MSED(NMES-2))*2
      ELSE
       NPMAX=NPOINT
      END IF

      IF(JF2 .LE. 0)   THEN
       IF(RRMAX .EQ. 0)   THEN
        EPS=1.
       ELSE
        EPS=EK(1)/RRMAX
        EPS=MAX(EPS,1.0E-12)
       END IF
      END IF

      IF( EXTPOL .GT. 0 )   THEN

       IF(JF2 .EQ. 1)   THEN
        IF(ERR1R .LE. EPS)   GO TO 7000
        IF( (NMES+ICOUNT.GE.MAXIT) .OR. (NPMAX.GT.NPOINT-2) )  THEN
         IF(NMES+ICOUNT.GE.MAXIT)   THEN
          WRITE(LUPRT,600) ICOUNT+NMES
CF8       WRITE(08,600) ICOUNT+NMES
         END IF
         IF(NPMAX.GT.NPOINT-2)   THEN
          WRITE(LUPRT,400)
CF8       WRITE(08,400)
         END IF
         EXTPOL=0
CF8      WRITE(08,340) NMES+ICOUNT
         DO 1600   M=1,MODQTY
         EK(M)=SQRT(MY(NMES,M))/H0 
 1600    CONTINUE
         GO TO 7000
        END IF

       ELSE

        IF(ERR1A .LE. EPS)   GO TO 7000

       END IF
 
      ELSE

       IF((JF2 .EQ. 1) .AND. (ERR2R .LE. EPS))   GO TO 7000
       IF((JF2 .EQ. 0) .AND. (ERR2A .LE. EPS))   GO TO 7000
       
      END IF

      IF(NMES+ICOUNT .GE. MAXIT)   THEN
       WRITE(LUPRT,600) ICOUNT+NMES
CF8    WRITE(08,600) ICOUNT+NMES
       IF(EXTPOL .GT. 0)   THEN
CF8     WRITE(08,410)
       ELSE
CF8     WRITE(08,420)
       END IF
       GO TO 7000
      END IF
 
      IF(NPMAX.GT.NPOINT-2)  THEN
CF8    WRITE(08,400)
        IF(EXTPOL. GT. 0)   THEN
CF8      WRITE(08,410)
        ELSE
CF8      WRITE(08,420)
        END IF
       GO TO 7000
      END IF

C   DEFINE NEW MESHES
      ICOUNT=ICOUNT+1

      IF(NMES .EQ. MAXMSH)   THEN
       DO 2030   MESH=1,NMES-1
       MH0(MESH)=MH0(MESH+1)
       DH0(MESH)=DH0(MESH+1)
       DH0SQ(MESH)=DH0SQ(MESH+1)
       MSED(MESH)=MSED(MESH+1)
       DSED(MESH)=DSED(MESH+1)
       DO 2030   M=1,MODQTY
       MY(MESH,M)=MY(MESH+1,M)
 2030  CONTINUE
      ELSE
       NMES=NMES+1
       ICOUNT=ICOUNT-1
      END IF

      MH0(NMES)= MH0(NMES-3)*2
      DH0(NMES)=1.0D0/DFLOAT(MH0(NMES))
      MH0SQ(NMES)=MH0(NMES)**2
      DH0SQ(NMES)=1.0D0/MH0SQ(NMES)
      IF(H1N.NE.0.0)   THEN
       MSED(NMES)= MSED(NMES-3)*2
       DSED(NMES)=H1N/DFLOAT(MSED(NMES))
      END IF
      I=NMES-1
      RETURN 1
 7000 CONTINUE 
CF8   IF(JF2 .NE. 2)   WRITE(08,620)EPS,ERR1A,ERR1R,ERR2A,ERR2R
      RETURN
      END
