      SUBROUTINE ATTENU(N,XI,VI,UN,UNP,NL,IZA,IZB,ALPBT,
     1  RHO,NBL,QN,H,FREQ,KNI,IERR)
C
C  SUBROUTINE TO CALCULATE THE IMAGINARY PART OF THE WAVE NUMBER
C   DUE TO BOTTOM ATTENUATION
C
C  AUTHOR: DALE D ELLIS
C          DEFENCE RESEARCH ESTABLISHMENT ATLANTIC
C          P.O. BOX 1012, DARTMOUTH, NS   B2Y 3Z7
C  DATE WRITTEN: 19-FEB-79
C  LAST MODIFICATION:
C  LAST EDIT   : 20-MAR-81
C
C  ARGUMENTS,
C  N            - NUMBER OF MODE (UNUSED)
C  XI(NL)       - ARRAY OF NORMALIZED DEPTHS
C  VI(NL)       - ARRAY OF NORMALIZED 'POTENTIAL'  (H*OMEGA/C(Z))**2
C  UN(NL)       - MODE FUNCTION AT DEPTHS XI(NL)
C  UNP(NL)      - DERIVATIVE OF MODE FUNCTION AT DEPTHS XI(NL)
C  NL           - TOTAL NUMBER OF LAYERS (INCLUDING BOTTOM LAYERS)
C  IZB          - LAYER AT WHICH INWARD INTEGRATION BEGINS
C  ALPBT(NBL)  - ATTENUATION IN THE BOTTOM LAYERS (DB/LENGTH-KHZ)
C  RHO(0:NBL)   - DENSITIES OF WATER COLUMN AND BOTTOM LAYERS
C  NBL          - NUMBER OF BOTTOM LAYERS
C  QN           - Q-ENERGY FOR MODE N  (I.E. EIGENVALUE)
C  H            - WATER DEPTH
C  FREQ         - FREQUENCY
C  KNI          - IMAGINARY PART OF WAVE NUMBER KN
C  IERR         - ERROR REPORTING PARAMETER (IERR=0 IF NO ERROR OCCURS)
C
      double precision pi
      PARAMETER (PI=3.1415926535897932384626433832795D0)
      INTEGER N,NL,IZA,IZB,NBL,IERR,NWL,MIN,MAX,I,II
      REAL ATTDEP,TOLU,TOLK,TOLGAM
      REAL KNI,FREQ,ALPWAT,ALPBT(NBL),RHO(0:NBL),
     1     ATNWAT,ATNSED,ATNSUB,ATNSUR,ATNBOT,ATNSHR,GRPVEL
      DOUBLE PRECISION XI(NL),VI(NL),UN(NL),UNP(NL),QN
      DOUBLE PRECISION ZERO,HALF,DKN,UIO,UIPO,H
      DOUBLE PRECISION USQINT,SUMWAT,SUMSED,SUMSUB,SUMGRP
      COMMON /TOL/ TOLK,TOLU,TOLGAM
      COMMON /ATTENS/ ATNWAT,ATNSED,ATNSUB,ATNSUR,ATNBOT,ATNSHR,GRPVEL
      DATA ZERO/0.D0/,  HALF/0.5D0/
C
      IERR=0
      NWL=NL-NBL
      DKN=ZERO
      SUMWAT = ZERO
      SUMSED = ZERO
      SUMSUB = ZERO
      SUMGRP = ZERO
C
C   CALCULATE ATTENUATION DUE TO ABSORPTION IN WATER
      MIN = IZA
      MAX = MIN0 (NWL,IZB-1)
C          ANYTHING ABOVE LAYER IZA IS IGNORED
      DO 10 I=MIN,MAX
      CALL LAYER (UN(I),UNP(I),VI(I)-QN,TOLGAM,XI(I+1)-XI(I),
     1  UIO,UIPO,USQINT,1)
      ALPWAT = ATTDEP ( SNGL(H*XI(I)), FREQ )
      SUMGRP = SUMGRP + VI(I)*USQINT
   10 SUMWAT = SUMWAT + ALPWAT * SQRT ( VI(I)/QN) * USQINT
      IF (MAX.LT.NWL)  THEN
         ALPWAT = ATTDEP ( SNGL(H*XI(I)), FREQ )
         USQINT = HALF * UN(I)**2 / SQRT (-VI(IZB)+QN)
         SUMWAT = SUMWAT + ALPWAT * SQRT (VI(IZB)/QN) * USQINT
         SUMGRP = SUMGRP + VI(IZB) * USQINT
      END IF
      SUMWAT = H / RHO(0) * SUMWAT
      SUMGRP = SUMGRP/RHO(0)
C
C   CALCULATE ATTENUATION DUE TO SEDIMENT LAYERS
   12 CONTINUE
      IF (IZB.LE.NWL) GO TO 30
      MIN = NWL + 1
      MAX = IZB-1
      IF (MIN.GT.MAX) GO TO 22
      DO 20 I=MIN,MAX
      II=I-NWL
      CALL LAYER (UN(I),UNP(I),VI(I)-QN,TOLGAM,XI(I+1)-XI(I),
     1  UIO,UIPO,USQINT,1)
      SUMGRP = SUMGRP + VI(I)*USQINT/RHO(II)
      IF (ALPBT(II).EQ.0) GO TO 20
      SUMSED = SUMSED + ALPBT(II)/RHO(II)*SQRT(VI(I)/QN)*USQINT
   20 CONTINUE
      SUMSED = SUMSED * H
      IF (MAX.EQ.NL-1) GO TO 22
C         BASEMENT LAYER IS TOO DEEP, STOP HERE
      USQINT =  HALF*UN(IZB)**2/SQRT(-VI(IZB)+QN)
      SUMGRP = SUMGRP + VI(IZB)*USQINT/RHO(IZB-NWL)
      SUMSED = SUMSED + ALPBT(IZB-NWL)/RHO(IZB-NWL)* H *
     1  SQRT(VI(IZB)/QN) * USQINT
      GO TO 30
C
C   CALCULATE ABSORPTION DUE TO BASEMENT LAYER
   22 CONTINUE
      IF (IZB.NE.NL)  IERR=1
      USQINT = HALF*UN(NL)**2/SQRT(-VI(NL)+QN)
      SUMGRP = SUMGRP + VI(NL)*USQINT/RHO(NBL)
      SUMSUB = H * ALPBT(NBL)/RHO(NBL) * SQRT (VI(NL)/QN)
     1 * USQINT
C
C   NOW ADD ALL THE ATTENUATIONS
C
   30 DKN = SUMWAT + SUMSED + SUMSUB
      ATNWAT = SUMWAT
      ATNSED = SUMSED
      ATNSUB = SUMSUB
      GRPVEL = 2.*PI*FREQ* SQRT(QN)/SUMGRP
      KNI=DKN
      RETURN
      END
