
      BLOCK DATA BDMDS
      INTEGER LUO,NMIN,ITMAX,IEF
      REAL VMIN,VMAX,TOLK,TOLU,TOLGAM
      LOGICAL EIGF,EIGV,TLFLG,ATTFLG,GVLFLG,CPFLG,PFFLG
 
      COMMON /PAR/     VMIN,VMAX,NMIN,ITMAX,IEF
      COMMON /TOL/    TOLK,TOLU,TOLGAM
      COMMON /PRTFLG/ LUO,EIGF,EIGV,TLFLG,ATTFLG,GVLFLG,CPFLG,PFFLG
 
      DATA VMIN/0.1/, VMAX/1E10/, NMIN/1/, ITMAX/30/, IEF/6/,
     1    TOLK/1E-8/, TOLU/1E-4/, TOLGAM/1E-4/, LUO/0/,
     2    EIGF,EIGV,TLFLG,ATTFLG,GVLFLG,CPFLG,PFFLG/7*.FALSE./
      END
