      SUBROUTINE INTOUT(ZI,CI,NL,NPT,Q,ZM,ZA,Z1,RHO,NBL,SUMA,WORK,
     2SMOUT,NZC,DELOUT,IERR)
C   FLAGS CHANGES BY DALE D ELLIS   NOV-78
      INTEGER I,ICHS,IZX,NBL,NL,NPT,NZC,IERR
      REAL DELOUT,GAM,GAM2,SSS,TOLU,TOLGAM,TOLK,RHO
      DIMENSION ZI(NL),CI(NL),RHO(0:NBL),WORK(NL,2)
      INTEGER ZA,ZM,Z1
      DOUBLE PRECISION WORK,GAMMA,GAMMA2,AI,BI,SS,SMOUT,A,B,S,C,E,RH,
     2    GSS,ZI,CI,Q,SUMA,PI
      COMMON/TOL/TOLK,TOLU,TOLGAM
      PARAMETER (PI=3.1415926535897932384626433832795D0)
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
C          THIS SUBROUTINE DOES THE FOLLOWING:
C       -PREFORMS THE OUTWARDS INTEGRATION , TO DETERMINE THE
C         EIGENFUNCTION & ITS DERIVATIVE FOR THE TRIAL EIGENVALUE
C         Q , FROM THE SURFACE TO THE LAYER CONTAINING THE MATCHING
C         RADIUS
C       -CALCULATES THE INTEGRAL OF THE EIGENFUNCTION SQUARED
C         DIVIDED BY THE DENSITY
C       -COUNTS THE NUMBER OF ZERO CROSSINGS OF THE EIGENFUNCTION
C         FROM THE SURFACE TO THE LAYER CONTAINING THE MATCHING RADIUS
C
C       INPUT VARIABLES:
C         ZI(NL),CI(NL),NL,NPT,Q,ZM,ZA,RHO(0:NBL),SUMA
C
C       OUTPUT VARIABLES:
C         WORK(NL,2),SMOUT,NZC,DELOUT
C
C       NOTES:
C         THE VALUE STORED IN WORK(I,*) IS THE VALUE AT THE TOP
C        OF LAYER I
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
C       INITIALIZE SMOUT & NZC
C       IF THE INTEGRATION STARTS AT THE SURFACE GO TO 50
C
      NZC=1
      SMOUT=0.0D0
      IF(ZA.EQ.1)GO TO 50
C
C       ASSIGN LEADING ZEROS
C       ASSIGN THE FIRST NON-ZERO ENTRY IN THE EIGENFUNCTION
C        & ITS DERIVATIVE
C
      DO 20 I=1,ZA-1
      WORK(I,1)=0.0D0
  20  WORK(I,2)=0.0D0
      GAMMA2=CI(ZA-1)-Q
      IF(DABS(GAMMA2).LT.TOLGAM)GAMMA2=TOLGAM
      GAMMA=DSQRT(DABS(GAMMA2))
      WORK(ZA,1)=DEXP(-SUMA)
      WORK(ZA,2)=WORK(ZA,1)*GAMMA
      RH=RHO(0)
      IF(ZA-1.GT.NPT)RH=RHO(ZA-NPT-1)
      SMOUT=SMOUT+WORK(ZA,1)*WORK(ZA,1)/GAMMA/2.0D0/RH
      IF(ZA.GT.NPT)WORK(ZA,2)=WORK(ZA,2)*RHO(ZA-NPT)/RH
      GO TO 100
C
C       IF THE INTEGRATION BEGINS AT THE SURFACE CALCULATE THE
C        FIRST ENTRY IN THE EIGENFUNCTION & ITS DERIVATIVE AT THAT
C        POINT
C
  50  WORK(1,1)=0.0D0
      GAMMA2=CI(1)-Q
      GAMMA=DSQRT(DABS(GAMMA2))
      IF(GAMMA2.LT.-TOLGAM.OR.GAMMA2.GT.TOLGAM)GO TO 60
      GAMMA2=CI(2)-Q
      WORK(1,2)=1.0D0
      IF(GAMMA2.LT.-TOLGAM)WORK(1,2)=DEXP(-SUMA/ZI(2))
      GO TO 100
  60  WORK(1,2)=GAMMA
      IF(CI(1).LT.Q)WORK(1,2)=WORK(1,2)*2.0D0*DEXP(-SUMA)
C
C       IF ZA=ZM THERE ARE NO MORE CALCULATIONS
C
  100 IF(ZA.EQ.ZM)RETURN
C
C       CALCULATE THE EIGENFUNCTION
C
      RH=RHO(0)
      DO 290 I=ZA+1,ZM
      GAMMA2=CI(I-1)-Q
      SS=ZI(I)-ZI(I-1)
      GAMMA=DSQRT(DABS(GAMMA2))
      IF(I.GT.NPT)RH=RHO(I-NPT)
C
C       DECIDE IF GAMMA SQUARED IS POSITIVE NEGATIVE OR ZERO
C        AND BRANCH TO THE APPROPRIATE TYPE OF SOLUTION FOR THE
C        LAYER UNDER CONSIDERATION
C
      IF(GAMMA2.GT.TOLGAM)GO TO 210
      IF(GAMMA2.LT.-TOLGAM)GO TO 230
C
C       USE A LINEAR SOLUTION IN THE LAYER
C       CALCULATE THE CONTRIBUTION TO SMOUT FOR THE LAYER
C
      AI=WORK(I-1,1)
      BI=WORK(I-1,2)
      WORK(I,1)=AI+SS*BI
      WORK(I,2)=BI
      SMOUT=SMOUT+(AI*AI*SS+AI*BI*SS*SS+BI*BI*(SS**3)/3.0D0)/RH
      GO TO 250
C
C       USE AN OSCILLATORY SOLUTION IN THE LAYER
C       CALCULATE THE INCREMENT TO SMOUT FOR THE LAYER
C
  210 AI=WORK(I-1,2)/GAMMA
      BI=WORK(I-1,1)
      GSS=GAMMA*SS
      S=DSIN(GSS)
      C=DCOS(GSS)
      WORK(I,1)=AI*S+BI*C
      WORK(I,2)=GAMMA*(AI*C-BI*S)
      SMOUT=SMOUT+SS/2.0D0/RH*((AI*AI+BI*BI)+S*C*(BI*BI-AI*AI)
     2/GSS+2.0D0*AI*BI*S*S/GSS)
      GO TO 250
C
C       USE AN EXPONENTIAL SOLUTION IN THE LAYER
C       CALCULATE SMOUT IN THE LAYER
C
  230 AI=0.5D0*(WORK(I-1,1)+WORK(I-1,2)/GAMMA)
      BI=0.5D0*(WORK(I-1,1)-WORK(I-1,2)/GAMMA)
      GSS=GAMMA*SS
      E=DEXP(GSS)
      WORK(I,1)=AI*E+BI/E
      WORK(I,2)=GAMMA*(AI*E-BI/E)
      SMOUT=SMOUT+SS/2.0D0/RH/GSS*(AI*AI*(E*E-1)+BI*BI*(1-1/E/E)+
     24.0D0*AI*BI*GSS)
C
C       IF THERE IS A CHANGE OF DENSITY IN THE NEXT LAYER
C        MULTIPLY THE DERIVATIVE BY THE DENSITY RATIO
C       IF WE ARE AT THE LAYER CONTAINING THE MATCHING RADIUS
C        CALCULATE DELOUT
C
  250 IF(I.GT.NPT)WORK(I,2)=WORK(I,2)*RHO(I-NPT)/RHO(I-NPT-1)
      IF(I.EQ.ZM)DELOUT=SNGL(DATAN2(WORK(I,1),WORK(I,2)/RH))
C
      IF (I.EQ.ZM) DELOUT=DELOUT + PI
  290         CONTINUE
C
C       COMMENCE WITH COUNTING THE NUMBER OF ZERO CROSSINGS
C
      DO 400 I=ZA,ZM-1
      SSS=SNGL(ZI(I+1)-ZI(I))
      GAM2=SNGL(CI(I)-Q)
      GAM=SQRT(ABS(GAM2))
      A=WORK(I+1,1)
      B=WORK(I,1)
C
C       IF A OR B IS ZERO SET IT TO + OR - 1 DEPENDING ON THE SIGN
C        OF THE DERIVATIVE AT THAT POINT
C
      IF(A.NE.0.0D0)GO TO 360
      A=1.0D0
      IF(WORK(I+1,2).LT.0.0D0)A=-A
  360 IF(B.NE.0.0D0)GO TO 370
      B=1.0D0
      IF(WORK(I,2).LT.0.0D0)B=-B
C
C       CHECK FOR A CHANGE IN THE SIGN OF THE EIGENFUNCTION BETWEEN
C        THE TOP & BOTTOM OF THE LAYER
C
  370 ICHS=0
      IF(A.GT.0.0D0.AND.B.LT.0.0D0.OR.B.GT.0.0D0.AND.A.LT.0.0D0)ICHS=1
C
C       FIND THE NUMBER OF ZERO CROSSINGS IF IN AN EXPONENTIAL REGION
C        OR A LINEAR REGION
C
      IF(GAM2.GT.TOLGAM)GO TO 390
      IF(ICHS.EQ.1)NZC=NZC+1
      GO TO 400
C
C       FIND THE NUMBER OF ZERO CROSSINGS IF IN AN OSCILLATORY REGION
C
  390 IZX = GAM*SSS/PI
      IF((IZX/2)*2.EQ.IZX.AND.ICHS.EQ.1.OR.(IZX/2)*2.NE.IZX.AND.
     2ICHS.EQ.0)IZX=IZX+1
      NZC=NZC+IZX
  400 CONTINUE
      RETURN
      END
