      SUBROUTINE KIRKFB (SIG1,RHO,UNZH,UNPZH,RKN,RK1SQ,DELKNB)
C
C  CALCULATES NORMAL MODE ATTENUATION DUE TO BOTTOM ROUGHNESS
C   USES THE KIRCHOFF APPROXIMATION A LA JENSEN-FERLA (SNAP-SM121)
C   (SUBROUTINE IS BASED ON KIRKFF (10/07/79) SURF SCATT
C
C  AUTHOR : DALE D ELLIS
C  DATE WRITTEN : APRIL 27,1980
C  LAST MODIFICATION : APRIL 28,1980
C
C INPUT PARAMETERS:
C  SIG1 - R.M.S. ROUGHNESS OF BOTTOM
C  RHO  - DENSITY IN WATER COLUMN
C  UNZH - MODE FUNCTION AT THE BOTTOM
C  UNPZH - DERIVATIVE OF MODE FUNCTION AT THE BOTTOM
C  RKN  - MODE WAVE NUMBER
C  RK1SQ -  WAVE NUMBER (SQUARED) OF SOUND SPEED AT THE BOTTOM
C
C OUTPUT PARAMETERS:
C  DELKNB - ATTENUATION COEFFICIENT (IMAGINARY PART OF KN)
C
C
      REAL BRAK,DELKNB,GAM1SQ,RHO,RK1SQ,RKN,SIG1,UNPZH,UNZH
      DELKNB=0.
      GAM1SQ=RK1SQ-RKN**2
C          NO ATTENUATION IF THE EQUIVALENT RAY DOES NOT INTERACT
C            WITH THE BOTTOM
      IF (GAM1SQ.LE.0.) RETURN
C
C          CALCULATE ATTENUATION COEFFICIENT FOR BOTTOM ROUGHNESS
C         (FRMLA (22) P.15 OF SACLANTCEN MEMO. SM-121  JAN 1979)
C
      BRAK=UNPZH**2 + (UNZH**2*GAM1SQ)
      DELKNB=SIG1**2*SQRT(GAM1SQ)/(2.*RKN*RHO) * BRAK
      RETURN
      END
