      SUBROUTINE NORMAL(UOUT,UDROUT,UIN,UDRIN,SMIN,SMOUT,RHO,NBL,ZM,
     2NPT,FACTOR,DELQ,IERR)
      INTEGER NBL,NPT,IERR,ZM
      REAL RHO(0:NBL)
      DOUBLE PRECISION UOUT,UDROUT,UIN,UDRIN,SMIN,SMOUT,FACTOR,RH,DELQ
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
C          THIS SUBROUTINE DOES THE FOLLOWING:
C       -NORMALIZES THE VALUES OF THE EIGENFUNCTION AT THE
C         MATCHING RADIUS
C       -CALCULATES DELQ
C
C       INPUT VARIABLES:
C         UOUT,UDROUT,UIN,UDRIN,SMIN,SMOUT,RHO(0:NBL),NBL,ZM
C
C       OUTPUT VARIABLES:
C         FACTOR,DELQ,UOUT,UDROUT,SMOUT
C
C       NOTES:
C         UOUT,UDROUT,SMOUT ARE INPUTED AS PREVIOUSLY CALCULATED
C        AND ARE OUTPUTED IN NORMALIZED FORM
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
C       NORMALIZE UOUT,UDROUT,SMOUT
C
      FACTOR=UIN/UOUT
      UOUT=FACTOR*UOUT
      UDROUT=FACTOR*UDROUT
      SMOUT=FACTOR*FACTOR*SMOUT
C
C       CALCULATE DELQ
C
      RH=RHO(0)
        IF(ZM.GT.NPT)RH=RHO(ZM-NPT)
      DELQ=UIN/RH*(UDRIN-UDROUT)/(SMIN+SMOUT)
      RETURN
      END
