      SUBROUTINE ARGNMB(N,NUMBER)

      INTEGER N,NUMBER,I
      CHARACTER*20 DUMMY
      EXTERNAL ARGGET,CHA2INT
      
      CALL ARGGET(N,DUMMY,I)
      CALL CHA2INT(DUMMY,NUMBER)
      
      RETURN
      END
