      FUNCTION ARGOPT(OPTION)

      LOGICAL       ARGOPT,CND1,CND2
      CHARACTER*(*) OPTION
      CHARACTER*40  DUMMY
      INTEGER       ILEN,OLEN,DLEN,LENSTR2,IARGC
      EXTERNAL      LENSTR2,IARGC,GETARG
      
      ARGOPT = .FALSE.
      ILEN = IARGC()

      IF(ILEN.LT.1) RETURN

      OLEN = LENSTR2(OPTION)
      IF(OLEN.EQ.0) RETURN

      DO 10 I=1,ILEN
         CALL GETARG(I,DUMMY)
         DLEN = LENSTR2(DUMMY)
         CND1 = DUMMY(1:1).EQ.'-'
         CND2 = DUMMY(2:DLEN).EQ.OPTION(1:OLEN)
         ARGOPT = CND1.AND.CND2
         IF(ARGOPT) RETURN
 10         CONTINUE

      RETURN
      END
