      SUBROUTINE ARGSUF(NAME,NLEN,SUFF)
      CHARACTER*(*) NAME,SUFF
      INTEGER       NLEN

      INTEGER       SLEN,LENSTR2
      LOGICAL       CND1,CND2,CND3

      EXTERNAL      LENSTR2

      NLEN = LENSTR2(NAME)
      SLEN = LENSTR2(SUFF)

      CND1 = NLEN.GT.SLEN
      CND2 = NAME(NLEN-SLEN+1:NLEN).EQ.SUFF(1:SLEN)
      CND3 = NAME(NLEN-SLEN:NLEN-SLEN).EQ.'.'
      IF(CND1.AND.CND2.AND.CND3) RETURN
      NAME(NLEN+1:NLEN+SLEN+1) = '.'//SUFF(1:SLEN)
      NLEN = LENSTR2(NAME)
      
      RETURN
      END
