      REAL*8 FUNCTION CDABS(Z)
C
C     THIS FUNCTION PROVIDES THE DOUBLE PRECISION COMPLEX ABSOLUTE
C
      IMPLICIT REAL*8 (A-H,O-Z)
      COMPLEX*16 Z
C
      CDABS=ZABS(Z)
C 
      RETURN
      END
