      COMPLEX*16 FUNCTION CDCOS(Z)
C
C     THIS FUNCTION PROVIDES THE DOUBLE PRECISION COMPLEX COSINE
C
      IMPLICIT REAL*8 (A-H,O-Z)
      COMPLEX*16 Z
C
      CDCOS=ZCOS(Z)
C 
      RETURN
      END
