      COMPLEX*16 FUNCTION CDEXP(Z)
C
C     THIS FUNCTION PROVIDES THE DOUBLE PRECISION COMPLEX EXPONENTIAL
C
      IMPLICIT REAL*8 (A-H,O-Z)
      COMPLEX*16 Z
C
      CDEXP=ZEXP(Z)
C 
      RETURN
      END
