      COMPLEX*16 FUNCTION CDSIN(Z)
C
C     THIS FUNCTION PROVIDES THE DOUBLE PRECISION COMPLEX SINE
C
      IMPLICIT REAL*8 (A-H,O-Z)
      COMPLEX*16 Z
C
      CDSIN=ZSIN(Z)
C 
      RETURN
      END
