      COMPLEX*16 FUNCTION CDSQRT(Z)
C
C     THIS FUNCTION PROVIDES THE DOUBLE PRECISION COMPLEX SQUARE ROOT
C
      IMPLICIT REAL*8 (A-H,O-Z)
      COMPLEX*16 Z
C
      CDSQRT=ZSQRT(Z)
C 
      RETURN
      END
